// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file k8s.io/api/autoscaling/v2/generated.proto (package k8s.io.api.autoscaling.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message k8s.io.api.autoscaling.v2.CrossVersionObjectReference
 */
export class CrossVersionObjectReference extends Message<CrossVersionObjectReference> {
  /**
   * @generated from field: string kind = 1;
   */
  kind = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string apiVersion = 3;
   */
  apiVersion = "";

  constructor(data?: PartialMessage<CrossVersionObjectReference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k8s.io.api.autoscaling.v2.CrossVersionObjectReference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "apiVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CrossVersionObjectReference {
    return new CrossVersionObjectReference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CrossVersionObjectReference {
    return new CrossVersionObjectReference().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CrossVersionObjectReference {
    return new CrossVersionObjectReference().fromJsonString(jsonString, options);
  }

  static equals(a: CrossVersionObjectReference | PlainMessage<CrossVersionObjectReference> | undefined, b: CrossVersionObjectReference | PlainMessage<CrossVersionObjectReference> | undefined): boolean {
    return proto3.util.equals(CrossVersionObjectReference, a, b);
  }
}

