// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file api/v1/environment/service.proto (package api.v1.environment, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetNamespacesRequest, GetNamespacesResponse, ListRequest, ListResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.environment.Service
 */
export const Service = {
  typeName: "api.v1.environment.Service",
  methods: {
    /**
     * List available environments.
     *
     * @generated from rpc api.v1.environment.Service.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.environment.Service.GetNamespaces
     */
    getNamespaces: {
      name: "GetNamespaces",
      I: GetNamespacesRequest,
      O: GetNamespacesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

