// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file api/v1/storage/settings/service.proto (package api.v1.storage.settings, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSettingsRequest, GetSettingsResponse, UpdateSettingsRequest, UpdateSettingsResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The service to manage storage
 *
 * @generated from service api.v1.storage.settings.Service
 */
export const Service = {
  typeName: "api.v1.storage.settings.Service",
  methods: {
    /**
     * @generated from rpc api.v1.storage.settings.Service.GetSettings
     */
    getSettings: {
      name: "GetSettings",
      I: GetSettingsRequest,
      O: GetSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.storage.settings.Service.UpdateSettings
     */
    updateSettings: {
      name: "UpdateSettings",
      I: UpdateSettingsRequest,
      O: UpdateSettingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

