// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file operator/api/v1/pipeline/service.proto (package api.v1.pipeline, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { GVK, ObjectStatusChange } from "./object_status_pb.js";

/**
 * @generated from enum api.v1.pipeline.ObjectOutcome
 */
export enum ObjectOutcome {
  /**
   * @generated from enum value: OBJECT_OUTCOME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: OBJECT_OUTCOME_CREATE = 1;
   */
  CREATE = 1,

  /**
   * @generated from enum value: OBJECT_OUTCOME_UPDATE = 2;
   */
  UPDATE = 2,

  /**
   * @generated from enum value: OBJECT_OUTCOME_DELETE = 3;
   */
  DELETE = 3,

  /**
   * @generated from enum value: OBJECT_OUTCOME_UNCHANGED = 4;
   */
  UNCHANGED = 4,

  /**
   * @generated from enum value: OBJECT_OUTCOME_ALREADY_EXISTS = 5;
   */
  ALREADY_EXISTS = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(ObjectOutcome)
proto3.util.setEnumType(ObjectOutcome, "api.v1.pipeline.ObjectOutcome", [
  { no: 0, name: "OBJECT_OUTCOME_UNSPECIFIED" },
  { no: 1, name: "OBJECT_OUTCOME_CREATE" },
  { no: 2, name: "OBJECT_OUTCOME_UPDATE" },
  { no: 3, name: "OBJECT_OUTCOME_DELETE" },
  { no: 4, name: "OBJECT_OUTCOME_UNCHANGED" },
  { no: 5, name: "OBJECT_OUTCOME_ALREADY_EXISTS" },
]);

/**
 * @generated from message api.v1.pipeline.WatchObjectStatusRequest
 */
export class WatchObjectStatusRequest extends Message<WatchObjectStatusRequest> {
  /**
   * @generated from field: string namespace = 1;
   */
  namespace = "";

  constructor(data?: PartialMessage<WatchObjectStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.WatchObjectStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "namespace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WatchObjectStatusRequest {
    return new WatchObjectStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WatchObjectStatusRequest {
    return new WatchObjectStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WatchObjectStatusRequest {
    return new WatchObjectStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: WatchObjectStatusRequest | PlainMessage<WatchObjectStatusRequest> | undefined, b: WatchObjectStatusRequest | PlainMessage<WatchObjectStatusRequest> | undefined): boolean {
    return proto3.util.equals(WatchObjectStatusRequest, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.WatchObjectStatusResponse
 */
export class WatchObjectStatusResponse extends Message<WatchObjectStatusResponse> {
  /**
   * @generated from field: api.v1.pipeline.ObjectStatusChange change = 1;
   */
  change?: ObjectStatusChange;

  constructor(data?: PartialMessage<WatchObjectStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.WatchObjectStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "change", kind: "message", T: ObjectStatusChange },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WatchObjectStatusResponse {
    return new WatchObjectStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WatchObjectStatusResponse {
    return new WatchObjectStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WatchObjectStatusResponse {
    return new WatchObjectStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: WatchObjectStatusResponse | PlainMessage<WatchObjectStatusResponse> | undefined, b: WatchObjectStatusResponse | PlainMessage<WatchObjectStatusResponse> | undefined): boolean {
    return proto3.util.equals(WatchObjectStatusResponse, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.DryRunRequest
 */
export class DryRunRequest extends Message<DryRunRequest> {
  /**
   * @generated from field: string namespace = 1;
   */
  namespace = "";

  /**
   * @generated from field: string capsule = 2;
   */
  capsule = "";

  /**
   * A YAML encoded OperatorConfig, to be used when processing the pipeline.
   *
   * @generated from field: string operator_config = 3;
   */
  operatorConfig = "";

  /**
   * An optional YAML encoded capsule spec, to be used instead of the current
   * one.
   *
   * @generated from field: string capsule_spec = 4;
   */
  capsuleSpec = "";

  /**
   * If force is enabled, existing resources will be handled as if they were
   * supposed to be replaced.
   *
   * @generated from field: bool force = 5;
   */
  force = false;

  /**
   * Additional objects to be considered materialized when performing the dryrun
   *
   * @generated from field: repeated api.v1.pipeline.Object additional_objects = 6;
   */
  additionalObjects: Object$[] = [];

  constructor(data?: PartialMessage<DryRunRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.DryRunRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "namespace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "capsule", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "operator_config", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "capsule_spec", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "force", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "additional_objects", kind: "message", T: Object$, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DryRunRequest {
    return new DryRunRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DryRunRequest {
    return new DryRunRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DryRunRequest {
    return new DryRunRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DryRunRequest | PlainMessage<DryRunRequest> | undefined, b: DryRunRequest | PlainMessage<DryRunRequest> | undefined): boolean {
    return proto3.util.equals(DryRunRequest, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.DryRunResponse
 */
export class DryRunResponse extends Message<DryRunResponse> {
  /**
   * @generated from field: repeated api.v1.pipeline.Object input_objects = 1;
   */
  inputObjects: Object$[] = [];

  /**
   * @generated from field: repeated api.v1.pipeline.ObjectChange output_objects = 2;
   */
  outputObjects: ObjectChange[] = [];

  constructor(data?: PartialMessage<DryRunResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.DryRunResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "input_objects", kind: "message", T: Object$, repeated: true },
    { no: 2, name: "output_objects", kind: "message", T: ObjectChange, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DryRunResponse {
    return new DryRunResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DryRunResponse {
    return new DryRunResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DryRunResponse {
    return new DryRunResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DryRunResponse | PlainMessage<DryRunResponse> | undefined, b: DryRunResponse | PlainMessage<DryRunResponse> | undefined): boolean {
    return proto3.util.equals(DryRunResponse, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.ObjectChange
 */
export class ObjectChange extends Message<ObjectChange> {
  /**
   * @generated from field: api.v1.pipeline.Object object = 1;
   */
  object?: Object$;

  /**
   * @generated from field: api.v1.pipeline.ObjectOutcome outcome = 2;
   */
  outcome = ObjectOutcome.UNSPECIFIED;

  constructor(data?: PartialMessage<ObjectChange>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.ObjectChange";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "object", kind: "message", T: Object$ },
    { no: 2, name: "outcome", kind: "enum", T: proto3.getEnumType(ObjectOutcome) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ObjectChange {
    return new ObjectChange().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ObjectChange {
    return new ObjectChange().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ObjectChange {
    return new ObjectChange().fromJsonString(jsonString, options);
  }

  static equals(a: ObjectChange | PlainMessage<ObjectChange> | undefined, b: ObjectChange | PlainMessage<ObjectChange> | undefined): boolean {
    return proto3.util.equals(ObjectChange, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.Object
 */
export class Object$ extends Message<Object$> {
  /**
   * @generated from field: api.v1.pipeline.GVK gvk = 1;
   */
  gvk?: GVK;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string content = 3;
   */
  content = "";

  constructor(data?: PartialMessage<Object$>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.Object";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "gvk", kind: "message", T: GVK },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Object$ {
    return new Object$().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Object$ {
    return new Object$().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Object$ {
    return new Object$().fromJsonString(jsonString, options);
  }

  static equals(a: Object$ | PlainMessage<Object$> | undefined, b: Object$ | PlainMessage<Object$> | undefined): boolean {
    return proto3.util.equals(Object$, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.DryRunPluginConfigRequest
 */
export class DryRunPluginConfigRequest extends Message<DryRunPluginConfigRequest> {
  /**
   * @generated from field: string namespace = 1;
   */
  namespace = "";

  /**
   * @generated from field: string capsule = 2;
   */
  capsule = "";

  /**
   * @generated from field: string operator_config = 3;
   */
  operatorConfig = "";

  /**
   * @generated from field: string capsule_spec = 4;
   */
  capsuleSpec = "";

  constructor(data?: PartialMessage<DryRunPluginConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.DryRunPluginConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "namespace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "capsule", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "operator_config", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "capsule_spec", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DryRunPluginConfigRequest {
    return new DryRunPluginConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DryRunPluginConfigRequest {
    return new DryRunPluginConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DryRunPluginConfigRequest {
    return new DryRunPluginConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DryRunPluginConfigRequest | PlainMessage<DryRunPluginConfigRequest> | undefined, b: DryRunPluginConfigRequest | PlainMessage<DryRunPluginConfigRequest> | undefined): boolean {
    return proto3.util.equals(DryRunPluginConfigRequest, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.DryRunPluginConfigResponse
 */
export class DryRunPluginConfigResponse extends Message<DryRunPluginConfigResponse> {
  /**
   * @generated from field: repeated api.v1.pipeline.StepConfig steps = 1;
   */
  steps: StepConfig[] = [];

  constructor(data?: PartialMessage<DryRunPluginConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.DryRunPluginConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "steps", kind: "message", T: StepConfig, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DryRunPluginConfigResponse {
    return new DryRunPluginConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DryRunPluginConfigResponse {
    return new DryRunPluginConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DryRunPluginConfigResponse {
    return new DryRunPluginConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DryRunPluginConfigResponse | PlainMessage<DryRunPluginConfigResponse> | undefined, b: DryRunPluginConfigResponse | PlainMessage<DryRunPluginConfigResponse> | undefined): boolean {
    return proto3.util.equals(DryRunPluginConfigResponse, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.StepConfig
 */
export class StepConfig extends Message<StepConfig> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: repeated api.v1.pipeline.PluginConfig plugins = 2;
   */
  plugins: PluginConfig[] = [];

  constructor(data?: PartialMessage<StepConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.StepConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "plugins", kind: "message", T: PluginConfig, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StepConfig {
    return new StepConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StepConfig {
    return new StepConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StepConfig {
    return new StepConfig().fromJsonString(jsonString, options);
  }

  static equals(a: StepConfig | PlainMessage<StepConfig> | undefined, b: StepConfig | PlainMessage<StepConfig> | undefined): boolean {
    return proto3.util.equals(StepConfig, a, b);
  }
}

/**
 * @generated from message api.v1.pipeline.PluginConfig
 */
export class PluginConfig extends Message<PluginConfig> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string config = 2;
   */
  config = "";

  /**
   * @generated from field: string err = 3;
   */
  err = "";

  constructor(data?: PartialMessage<PluginConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.pipeline.PluginConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "config", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "err", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PluginConfig {
    return new PluginConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PluginConfig {
    return new PluginConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PluginConfig {
    return new PluginConfig().fromJsonString(jsonString, options);
  }

  static equals(a: PluginConfig | PlainMessage<PluginConfig> | undefined, b: PluginConfig | PlainMessage<PluginConfig> | undefined): boolean {
    return proto3.util.equals(PluginConfig, a, b);
  }
}

